/**
 * @file NumberSequenceRepository.ts
 * @description Atomic, self-seeding allocator for the human-readable numbers
 *   carried by incidents (`INC-YYYY-NNN`) and approval requests
 *   (`APR-YYYY-NNNNN`).
 * @feature compliance
 *
 * Both were previously generated by reading the current maximum with a string
 * `orderBy` and adding one (TASK-287). That is wrong twice over:
 *
 *   - Lexicographically, `INC-2026-999` sorts above `INC-2026-1000`, so the
 *     thousandth incident of a year recomputes a number that already exists and
 *     every later one collides forever. This bites with multi-tenancy off.
 *   - Under multi-tenancy the read is scoped to the caller's tenant while the
 *     column is globally unique, so a second tenant computes `INC-2026-001`,
 *     hits the first tenant's row, and never advances past it.
 *
 * The replacement is a counter row per `(scope, tenantKey, year)` incremented
 * inside a transaction. The number it returns is an integer, so the rendering
 * side owns the padding and the lexicographic trap cannot come back.
 */

import { prisma } from '../database/index.js';
import { getTenantId } from '../middleware/tenantContext.js';

/** The two numbering series this allocator serves. */
export type NumberScope = 'incident' | 'approval';

/** Outside any tenant scope — background jobs, seeds, single-tenant mode. */
const DEFAULT_TENANT_KEY = 'default';

/** Prefix of the rendered number, which is also how the seed is recognised. */
export function numberPrefix(scope: NumberScope, year: number): string {
  return scope === 'incident' ? `INC-${year}-` : `APR-${year}-`;
}

/**
 * The value a brand-new counter row starts at.
 *
 * Runs only when no counter exists for this tenant and year, and reads the
 * numbers already in the table so an existing database resumes from where it
 * was rather than restarting at 1. The maximum is taken **numerically**, which
 * is the same bug fixed a second time: a string maximum would hand back 999
 * on a table that already holds 1000.
 */
async function computeSeed(
  tx: TransactionClient,
  scope: NumberScope,
  year: number
): Promise<number> {
  const prefix = numberPrefix(scope, year);

  const existing: string[] =
    scope === 'incident'
      ? (
          await tx.incident.findMany({
            where: { incidentNumber: { startsWith: prefix } },
            select: { incidentNumber: true },
          })
        ).map((row) => row.incidentNumber)
      : (
          await tx.approvalRequest.findMany({
            where: { requestNumber: { startsWith: prefix } },
            select: { requestNumber: true },
          })
        ).map((row) => row.requestNumber);

  let max = 0;
  for (const number of existing) {
    const parsed = Number.parseInt(number.slice(prefix.length), 10);
    if (Number.isFinite(parsed) && parsed > max) max = parsed;
  }
  return max + 1;
}

/**
 * The interactive-transaction client. Prisma exports this as
 * `Prisma.TransactionClient`, but importing the namespace only for a callback
 * parameter pulls the whole generated type surface into this module; the two
 * models the seed reads are all that is needed.
 */
type TransactionClient = {
  incident: {
    findMany: (args: {
      where: { incidentNumber: { startsWith: string } };
      select: { incidentNumber: true };
    }) => Promise<Array<{ incidentNumber: string }>>;
  };
  approvalRequest: {
    findMany: (args: {
      where: { requestNumber: { startsWith: string } };
      select: { requestNumber: true };
    }) => Promise<Array<{ requestNumber: string }>>;
  };
  numberSequence: {
    findUnique: (args: {
      where: { scope_tenantKey_year: { scope: string; tenantKey: string; year: number } };
    }) => Promise<{ value: number } | null>;
    upsert: (args: {
      where: { scope_tenantKey_year: { scope: string; tenantKey: string; year: number } };
      update: { value: { increment: number } };
      create: { scope: string; tenantKey: string; year: number; value: number };
    }) => Promise<{ value: number }>;
  };
};

/**
 * Claim the next number in a series for the current tenant and calendar year.
 *
 * `NumberSequence` deliberately carries no `tenantId` column and is absent from
 * `TENANT_SCOPED_MODELS` (server/src/database/client.ts) — the tenant lives in
 * the `tenantKey` half of the primary key instead, so the isolation extension
 * must leave these queries alone rather than try to stamp a column that is not
 * there.
 *
 * @param scope - which series to draw from
 * @returns the year the number belongs to and its integer value (1-based)
 */
export async function allocateNumber(
  scope: NumberScope
): Promise<{ year: number; value: number }> {
  const year = new Date().getFullYear();
  const tenantKey = getTenantId() ?? DEFAULT_TENANT_KEY;
  const key = { scope_tenantKey_year: { scope, tenantKey, year } };

  const value = await (
    prisma as unknown as {
      $transaction: <T>(fn: (tx: TransactionClient) => Promise<T>) => Promise<T>;
    }
  ).$transaction(async (tx) => {
    const current = await tx.numberSequence.findUnique({ where: key });
    // The seed is the create path's value and is never computed when a counter
    // already exists — scanning the table on every allocation would put the
    // cost this change removes straight back.
    const seed = current ? 0 : await computeSeed(tx, scope, year);

    const row = await tx.numberSequence.upsert({
      where: key,
      update: { value: { increment: 1 } },
      create: { scope, tenantKey, year, value: seed },
    });
    return row.value;
  });

  return { year, value };
}

/**
 * Allocate and render in one step — `INC-2026-007`, `APR-2026-00042`.
 *
 * @param scope - which series to draw from
 * @param pad - digits to zero-pad the counter to (3 incidents, 5 approvals).
 *   Padding is presentation only: a counter past the padding width renders
 *   wider rather than wrapping, which is exactly what the old generator got
 *   wrong.
 */
export async function allocateFormattedNumber(
  scope: NumberScope,
  pad: number
): Promise<string> {
  const { year, value } = await allocateNumber(scope);
  return `${numberPrefix(scope, year)}${String(value).padStart(pad, '0')}`;
}
